system:
  env: public
  addr: 8888
  db-type: mysql
zap:
  level: info
  format: console
  prefix: '[KING]'
  director: log
  link-name: latest_log
  showLine: true
  encode-level: LowercaseColorLevelEncoder
  stacktrace-key: stacktrace
  log-in-console: true
mysql:
  path: 172.27.15.125:3306
  config: charset=utf8mb4&parseTime=True&loc=Local
  db-name: yamaidie
  username: root
  password: nBqYwcAq^MJCx^KJ
  max-idle-conns: 0
  max-open-conns: 0
  log-mode: ""
  log-zap: false